# Generated by Django 2.2.7 on 2019-11-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='学校名称')),
            ],
            options={
                'db_table': 't_school',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuNo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, choices=[('1', '男'), ('2', '女'), ('3', '保密')], help_text='请输入（1：男，2：女，3：保密）', max_length=1, null=True, verbose_name='性别')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.School')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生信息',
                'db_table': 't_student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='bbs.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='computer_name', max_length=100, verbose_name='电脑名称')),
                ('stu', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Student')),
            ],
            options={
                'db_table': 't_computer',
            },
        ),
    ]
