# Generated by Django 2.2.7 on 2019-11-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, db_table='t_tea_stu', to='bbs.Student'),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='t_teacher',
        ),
    ]
